baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "Felix Wang Space"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"
    userName = "felix.wang"
    pcName = "myPortal"
    workDir = "discovery"
    profile = "profile.txt"
    ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
    stdoutDelay = 15 # stdout speed : [description] , files in Params.Tree
    commandDelay = 15 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/
   description = "/description.md"

    [Params.Tree]
    use = true
    folderName="Discovery"
    files = [
        ["Blogs", "https://felixwqp.github.io"],
        ["Linkedin", "https://www.linkedin.com/in/felix-wang-5a171312b/"],
        #["Go", "/works/go.md"],
        #["Hugo", "/works/hugo.md"]
    ]
